services:
  backend:
    build: ./Backend
    ports:
      - "80:80"
    environment:
      - ENV=production
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge