"""Updating imageUrl to accept no values and use default

Revision ID: 2c709b96a150
Revises: f0b1233a55fa
Create Date: 2025-02-06 07:50:54.480905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c709b96a150'
down_revision: Union[str, None] = 'f0b1233a55fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
