"""Created campuses table

Revision ID: 821384c1c9cb
Revises: bfa4c39263a6
Create Date: 2025-02-09 22:04:34.680869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821384c1c9cb'
down_revision: Union[str, None] = 'bfa4c39263a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campuses', sa.Column('imageUrl', sa.String(), nullable=False))
    op.add_column('campuses', sa.Column('address', sa.String(), nullable=False))
    op.add_column('campuses', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campuses', 'description')
    op.drop_column('campuses', 'address')
    op.drop_column('campuses', 'imageUrl')
    # ### end Alembic commands ###
