"""creating one to many relationship between student and campus

Revision ID: 97af52e3649a
Revises: 9bc210386c55
Create Date: 2025-02-10 01:03:37.248235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97af52e3649a'
down_revision: Union[str, None] = '9bc210386c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campuses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('students', sa.Column('campus_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'campuses', ['campus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'campus_id')
    op.alter_column('campuses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
