"""Added missing name field in campuses table

Revision ID: 9bc210386c55
Revises: 821384c1c9cb
Create Date: 2025-02-09 22:12:10.964827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc210386c55'
down_revision: Union[str, None] = '821384c1c9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campuses', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campuses', 'name')
    # ### end Alembic commands ###
