"""Making campus_id optional on post

Revision ID: a73ee1581210
Revises: 97af52e3649a
Create Date: 2025-02-19 19:07:16.472992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73ee1581210'
down_revision: Union[str, None] = '97af52e3649a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'campus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'campus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
