"""Changing imgUrl from default to server_default

Revision ID: aee8d2d50999
Revises: 2c709b96a150
Create Date: 2025-02-06 19:55:16.392039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee8d2d50999'
down_revision: Union[str, None] = '2c709b96a150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
