"""tweaking imgURL to allow default

Revision ID: bfa4c39263a6
Revises: aee8d2d50999
Create Date: 2025-02-06 20:21:41.802832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa4c39263a6'
down_revision: Union[str, None] = 'aee8d2d50999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
